
// This file has been generated by the GUI designer. Do not modify.
namespace LevelEditor
{
	public partial class MapEditor
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action LoadMapAction;
		private global::Gtk.Action SaveMapAction;
		private global::Gtk.Action Action;
		private global::Gtk.Action ExitAction;
		private global::Gtk.Action ToolsAction;
		private global::Gtk.Action ClearMapAction;
		private global::Gtk.Action LayerAction;
		private global::Gtk.Action BackgroundAction;
		private global::Gtk.Action InteractiveAction;
		private global::Gtk.Action ForegroundAction;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.FileChooserButton filechooserbutton1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.VBox vbox1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LevelEditor.MapEditor
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.LoadMapAction = new global::Gtk.Action ("LoadMapAction", global::Mono.Unix.Catalog.GetString ("Load Map"), null, null);
			this.LoadMapAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load Map");
			w1.Add (this.LoadMapAction, null);
			this.SaveMapAction = new global::Gtk.Action ("SaveMapAction", global::Mono.Unix.Catalog.GetString ("Save Map"), null, null);
			this.SaveMapAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Map");
			w1.Add (this.SaveMapAction, null);
			this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("-"), null, null);
			this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("-");
			w1.Add (this.Action, null);
			this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
			this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.ExitAction, null);
			this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
			this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
			w1.Add (this.ToolsAction, null);
			this.ClearMapAction = new global::Gtk.Action ("ClearMapAction", global::Mono.Unix.Catalog.GetString ("Clear Map"), null, null);
			this.ClearMapAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clear Map");
			w1.Add (this.ClearMapAction, null);
			this.LayerAction = new global::Gtk.Action ("LayerAction", global::Mono.Unix.Catalog.GetString ("Layer"), null, null);
			this.LayerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Layer");
			w1.Add (this.LayerAction, null);
			this.BackgroundAction = new global::Gtk.Action ("BackgroundAction", global::Mono.Unix.Catalog.GetString ("Background"), null, null);
			this.BackgroundAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Background");
			w1.Add (this.BackgroundAction, null);
			this.InteractiveAction = new global::Gtk.Action ("InteractiveAction", global::Mono.Unix.Catalog.GetString ("Interactive"), null, null);
			this.InteractiveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Interactive");
			w1.Add (this.InteractiveAction, null);
			this.ForegroundAction = new global::Gtk.Action ("ForegroundAction", global::Mono.Unix.Catalog.GetString ("Foreground"), null, null);
			this.ForegroundAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Foreground");
			w1.Add (this.ForegroundAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 500;
			this.HeightRequest = 500;
			this.Name = "LevelEditor.MapEditor";
			this.Title = global::Mono.Unix.Catalog.GetString ("MapEditor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(9));
			this.AllowShrink = true;
			this.DefaultWidth = 500;
			this.DefaultHeight = 500;
			// Container child LevelEditor.MapEditor.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.CanDefault = true;
			this.fixed2.CanFocus = true;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='LoadMapAction' action='LoadMapAction'/><menuitem name='SaveMapAction' action='SaveMapAction'/><menuitem name='Action' action='Action'/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='ToolsAction' action='ToolsAction'><menuitem name='ClearMapAction' action='ClearMapAction'/></menu><menu name='LayerAction' action='LayerAction'><menuitem name='BackgroundAction' action='BackgroundAction'/><menuitem name='InteractiveAction' action='InteractiveAction'/><menuitem name='ForegroundAction' action='ForegroundAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.WidthRequest = 490;
			this.menubar1.Name = "menubar1";
			this.fixed2.Add (this.menubar1);
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.filechooserbutton1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Seleccionar un archivo"), ((global::Gtk.FileChooserAction)(0)));
			this.filechooserbutton1.WidthRequest = 200;
			this.filechooserbutton1.Name = "filechooserbutton1";
			this.fixed2.Add (this.filechooserbutton1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.filechooserbutton1]));
			w3.X = 290;
			w3.Y = 450;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 300;
			this.GtkScrolledWindow.HeightRequest = 300;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w4 = new global::Gtk.Viewport ();
			w4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			w4.Add (this.vbox1);
			this.GtkScrolledWindow.Add (w4);
			this.fixed2.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.GtkScrolledWindow]));
			w7.X = 9;
			w7.Y = 27;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.fixed2.HasDefault = true;
			this.Show ();
			this.ExitAction.Activated += new global::System.EventHandler (this.exitToolStripMenuItem_Click);
		}
	}
}
