/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unison.lcc.plandeestudios;

import javax.swing.UnsupportedLookAndFeelException;
import unison.lcc.plandeestudios.guis.AltaDeAlumno;
import unison.lcc.plandeestudios.guis.AltaDeMaestro;
import unison.lcc.plandeestudios.guis.AltaDeMateria;

/**
 *
 * @author Roberto Montaño
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbMateria = new javax.swing.JButton();
        jbAlumno = new javax.swing.JButton();
        jbMaestro = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Plan LCC");

        jbMateria.setText("Dar materia de alta");
        jbMateria.addActionListener(formListener);

        jbAlumno.setText("Dar alumno de alta");
        jbAlumno.addActionListener(formListener);

        jbMaestro.setText("Dar maestro de alta");
        jbMaestro.addActionListener(formListener);

        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbMaestro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jbCerrar)
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jbMateria) {
                Principal.this.jbMateriaActionPerformed(evt);
            }
            else if (evt.getSource() == jbCerrar) {
                Principal.this.jbCerrarActionPerformed(evt);
            }
            else if (evt.getSource() == jbAlumno) {
                Principal.this.jbAlumnoActionPerformed(evt);
            }
            else if (evt.getSource() == jbMaestro) {
                Principal.this.jbMaestroActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMateriaActionPerformed
        // TODO add your handling code here:
        new AltaDeMateria().setVisible(true);
    }//GEN-LAST:event_jbMateriaActionPerformed

    private void jbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlumnoActionPerformed
        // TODO add your handling code here:
        new AltaDeAlumno().setVisible(true);
    }//GEN-LAST:event_jbAlumnoActionPerformed

    private void jbMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMaestroActionPerformed
        // TODO add your handling code here:
        new AltaDeMaestro().setVisible(true);
    }//GEN-LAST:event_jbMaestroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       // TODO code application logic here
        try{
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if("GTK+".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex){}
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlumno;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbMaestro;
    private javax.swing.JButton jbMateria;
    // End of variables declaration//GEN-END:variables
}
